# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
    - main
    - dev
    - stage*
  pull_request:
    branches:
    - main
    - dev
    - stage*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with untittest
      run: |
        if [ -d tests ]; then python -m unittest discover -s ./tests -p *Test.py; fi
